apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: aws-run-
spec:
  taskRef:
    name: aws-cli
  params:
    - name: SCRIPT
      value: |
        aws $1 mb s3://$2
    - name: ARGS
      value:
        - s3
        - geoallen-taskrun-test
  workspaces:
    - name: secrets
      secret:
        secretName: aws-secret
    - name: source
      emptyDir: {}
      